Imported GNU-R version 67000 from http://svn.r-project.org/R/trunk

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1171,6 +1171,7 @@ with_system_pcre
 with_system_tre
 with_system_xz
 with_valgrind_instrumentation
+with_system_valgrind_headers
 with_internal_tzcode
 with_recommended_packages
 with_ICU
@@ -1929,7 +1930,9 @@ Optional Packages:
   --with-system-xz        use system xz (lzma) library (if available) [yes]
   --with-valgrind-instrumentation
                           Level of additional instrumentation for Valgrind
-                          (0/1/2) [0]
+                          (0/1/2/3) [0]
+  --with-system-valgrind-headers
+                          use system valgrind headers (if available) [no]
   --with-internal-tzcode  use internal time-zone code [no]
   --with-recommended-packages
                           use/install recommended R packages [yes]
@@ -4315,6 +4318,20 @@ fi
 
 
 
+# Check whether --with-system-valgrind-headers was given.
+if test "${with_system_valgrind_headers+set}" = set; then :
+  withval=$with_system_valgrind_headers; if test "${withval}" = no; then
+  use_system_valgrind=no
+else
+  use_system_valgrind=yes
+fi
+
+else
+  use_system_valgrind=no
+fi
+
+
+
 # Check whether --with-internal-tzcode was given.
 if test "${with_internal_tzcode+set}" = set; then :
   withval=$with_internal_tzcode; use_internal_tzcode=${withval}
@@ -5429,7 +5446,7 @@ if test -n "${KPSEWHICH}"; then
 $as_echo "found zi4.sty" >&6; }
   else
     ${KPSEWHICH} inconsolata.sty > /dev/null
-    if test $? -ne 0; then
+    if test $? -eq 0; then
       { $as_echo "$as_me:${as_lineno-$LINENO}: result: found inconsolata.sty" >&5
 $as_echo "found inconsolata.sty" >&6; }
     else
@@ -9089,13 +9106,13 @@ if ${lt_cv_nm_interface+:} false; then :
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:9092: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:9109: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:9095: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:9112: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:9098: output\"" >&5)
+  (eval echo "\"\$as_me:9115: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -11947,11 +11964,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11950: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11967: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11954: \$? = $ac_status" >&5
+   echo "$as_me:11971: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12286,11 +12303,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12289: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12306: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12293: \$? = $ac_status" >&5
+   echo "$as_me:12310: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12391,11 +12408,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12394: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12411: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12398: \$? = $ac_status" >&5
+   echo "$as_me:12415: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12446,11 +12463,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12449: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12466: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12453: \$? = $ac_status" >&5
+   echo "$as_me:12470: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14813,7 +14830,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 14816 "configure"
+#line 14833 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14909,7 +14926,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 14912 "configure"
+#line 14929 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16858,11 +16875,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16861: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16878: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16865: \$? = $ac_status" >&5
+   echo "$as_me:16882: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16957,11 +16974,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16960: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16977: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16964: \$? = $ac_status" >&5
+   echo "$as_me:16981: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17009,11 +17026,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17012: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17029: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17016: \$? = $ac_status" >&5
+   echo "$as_me:17033: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18389,11 +18406,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18392: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18409: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18396: \$? = $ac_status" >&5
+   echo "$as_me:18413: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18488,11 +18505,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18491: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18508: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18495: \$? = $ac_status" >&5
+   echo "$as_me:18512: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18540,11 +18557,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18543: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18560: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18547: \$? = $ac_status" >&5
+   echo "$as_me:18564: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21512,6 +21529,7 @@ fi
 ## fpu_control.h is only used on Linux, for the obsolete __setfpucw.
 ## sys/param.h is one way to get PATH_MAX.
 ## sched.h is POSIX, but we use it for Linux-specific features (affinity)
+## stdalign.h is C11.
 for ac_header in arpa/inet.h dl.h dlfcn.h elf.h fcntl.h floatingpoint.h \
   fpu_control.h glob.h grp.h langinfo.h \
   netdb.h netinet/in.h pwd.h sched.h strings.h \
@@ -21530,6 +21548,19 @@ fi
 done
 
 ## </NOTE>
+## stdalign.h is C11.
+for ac_header in stdalign.h
+do :
+  ac_fn_c_check_header_mongrel "$LINENO" "stdalign.h" "ac_cv_header_stdalign_h" "$ac_includes_default"
+if test "x$ac_cv_header_stdalign_h" = xyes; then :
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_STDALIGN_H 1
+_ACEOF
+
+fi
+
+done
+
 ## <NOTE>
 ## These are C99 headers but some C code (written to work also
 ## without assuming C99) may need the corresponding conditionals.
@@ -23255,7 +23286,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_verb"
-(eval echo $as_me:23258: \"$ac_link\") >&5
+(eval echo $as_me:23289: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -23330,7 +23361,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_cv_prog_c_v"
-(eval echo $as_me:23333: \"$ac_link\") >&5
+(eval echo $as_me:23364: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -29607,66 +29638,6 @@ $as_echo "#define HAVE_TM_GMTOFF 1" >>confdefs.h
 
 fi
 
-
-## check for vecLib framework (potentially to be used for BLAS)
-## in theory vecLib is platform-independent, in practice only
-## Apple's OS X is known to provide it
- { $as_echo "$as_me:${as_lineno-$LINENO}: checking for cblas_cdotu_sub in vecLib framework" >&5
-$as_echo_n "checking for cblas_cdotu_sub in vecLib framework... " >&6; }
-if ${r_cv_check_fw_vecLib+:} false; then :
-  $as_echo_n "(cached) " >&6
-else
-  r_cv_check_fw_save_LIBS=$LIBS
-  r_cv_check_fw_vecLib=no
-  LIBS="-framework vecLib  $LIBS"
-  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char cblas_cdotu_sub ();
-#ifdef F77_DUMMY_MAIN
-
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-
-#endif
-int
-main ()
-{
-return cblas_cdotu_sub ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"; then :
-  r_cv_check_fw_vecLib="-framework vecLib"
-fi
-rm -f core conftest.err conftest.$ac_objext \
-    conftest$ac_exeext conftest.$ac_ext
-  LIBS=$r_cv_check_fw_save_LIBS
-  if test "$r_cv_check_fw_vecLib" != no; then :
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_VECLIB_FW 1
-_ACEOF
-
-	have_vecLib_fw=yes
-else
-  have_vecLib_fw=no
-fi
-
-fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $r_cv_check_fw_vecLib" >&5
-$as_echo "$r_cv_check_fw_vecLib" >&6; }
-
-
 ## BLAS.
 ## <NOTE>
 ## This has to come *after* checking for Fortran 77 compiler/converter
@@ -30247,8 +30218,9 @@ fi
 fi
 
 ## Now check if zdotu works (fails on AMD64 with the wrong compiler;
-## also fails on OS X with vecLib and gfortran; but in that case we
-## have a work-around using USE_VECLIB_G95FIX)
+## also fails on OS X with Accelerate/vecLib and gfortran;
+## but in that case we have a work-around using USE_VECLIB_G95FIX)
+
 if test "${acx_blas_ok}" = yes; then
   { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether double complex BLAS can be used" >&5
 $as_echo_n "checking whether double complex BLAS can be used... " >&6; }
@@ -30324,20 +30296,20 @@ fi
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
   else
-    ## NB: this lot is not cached
-    if test "${r_cv_check_fw_vecLib}" != "no"; then
-      { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+    case "${BLAS_LIBS}" in
+      *Accelerate* | *vecLib*)
+        ## for vecLib we have a work-around by using cblas_..._sub
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
-      ## for vecLib we have a work-around by using cblas_..._sub
-      use_veclib_g95fix=yes
-      ## The fix may not work with internal lapack, but
-      ## is more likely to in R >= 2.15.2.
-    else
-      { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+        use_veclib_g95fix=yes
+        ;;
+      *)
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-      BLAS_LIBS=
-      acx_blas_ok="no"
-    fi
+        BLAS_LIBS=
+        acx_blas_ok="no"
+        ;;
+    esac
   fi
 fi
 if test "${acx_blas_ok}" = yes; then
@@ -35235,7 +35207,21 @@ if test ${valgrind_level} -eq 0; then
 
 $as_echo "#define NVALGRIND 1" >>confdefs.h
 
+elif test "${use_system_valgrind}" = yes; then
+  for ac_header in valgrind/memcheck.h
+do :
+  ac_fn_c_check_header_mongrel "$LINENO" "valgrind/memcheck.h" "ac_cv_header_valgrind_memcheck_h" "$ac_includes_default"
+if test "x$ac_cv_header_valgrind_memcheck_h" = xyes; then :
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_VALGRIND_MEMCHECK_H 1
+_ACEOF
+
 fi
+
+done
+
+fi
+
 
 cat >>confdefs.h <<_ACEOF
 #define VALGRIND_LEVEL ${valgrind_level}
@@ -36490,11 +36476,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:36493: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:36479: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:36497: \$? = $ac_status" >&5
+   echo "$as_me:36483: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -36589,11 +36575,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:36592: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:36578: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:36596: \$? = $ac_status" >&5
+   echo "$as_me:36582: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -36641,11 +36627,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:36644: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:36630: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:36648: \$? = $ac_status" >&5
+   echo "$as_me:36634: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -46056,10 +46042,14 @@ if test "${acx_blas_ok}" = "yes"; then
   ## Try to figure out which BLAS was used.
   case "${BLAS_LIBS0}" in
     *-latlas*) r_blas=ATLAS ;;
+    *-lgoto*) r_blas=Goto ;;
+    *-lopenblas*) r_blas=OpenBLAS ;;
+    *-lacml*) r_blas=ACML ;;
+    *-lmkl*) r_blas=MKL ;;
     *-lsgemm*) r_blas=PhiPack ;;
     *sunperf*) r_blas=SunPerf ;;
     *-lessl*)  r_blas=ESSL ;;
-    *vecLib*)  r_blas=vecLib ;;
+    *Accelerate*)  r_blas=Accelerate ;;
     "")        r_blas=none ;;
     *)         r_blas=generic ;;
   esac
