Imported GNU-R version 86483.

diff --git a/tests/Makefile.common b/tests/Makefile.common
--- a/tests/Makefile.common
+++ b/tests/Makefile.common
@@ -228,13 +228,13 @@ test-Packages:
 
 ## R_PKGS_BASE is from ../share/make/vars.mk
 test-Packages1:
-	@for p in $(R_PKGS_BASE); do \
+	@fail=; for p in $(R_PKGS_BASE); do \
 	  $(ECHO) "checking package '$${p}'"; \
 	  _R_CHECK_FF_CALLS_=registration \
 	  _R_CHECK_CODE_USAGE_WITH_ONLY_BASE_ATTACHED_=true \
-	  $(top_builddir)/bin/R CMD check --install=skip --no-build-vignettes \
-	    $(top_srcdir)/src/library/$${p} || $(ECHO); \
-	done
+	  $(RCHK) --install=skip --no-build-vignettes \
+	    $(top_srcdir)/src/library/$${p} || fail="$${fail} $${p}"; \
+	done; if test -n "$${fail}"; then $(ECHO) "FAILED:$${fail}"; exit 1; fi
 
 PKG_OBJECTS = $(R_PKGS_BASE:=.log)
 
@@ -251,8 +251,8 @@ stamp-Packages: $(PKG_OBJECTS)
 	@rm -f $@
 	@_R_CHECK_FF_CALLS_=registration \
 	  _R_CHECK_CODE_USAGE_WITH_ONLY_BASE_ATTACHED_=true \
-	  $(top_builddir)/bin/R CMD check --install=skip --no-build-vignettes \
-	  $(top_srcdir)/src/library/`basename $@ .log` > $@ 2>&1
+	  $(RCHK) --install=skip --no-build-vignettes \
+	  $(top_srcdir)/src/library/`basename $@ .log` > $@ 2>&1 || (cat $@ && exit 1)
 	@cat $@
 
 test-Gct: $(test-out-gct)
@@ -334,7 +334,7 @@ test-Regexp:
 test-Segfault:
 	@$(ECHO) "running tests to possibly trigger segfaults"
 	@$(MK) $(test-out-segfault) RVAL_IF_DIFF=0
-	-@rm -Rf data dumpdata.R ./-package.Rd ./-Ex.R .Rd F.Rd [a-z]*0.Rd Rprof.out Rplots* \
+	-@rm -Rf data dumpdata.R ./-package.Rd ./-Ex.R .Rd l0.Rd m0.Rd df0.Rd Rprof.out Rplots* \
 	    PACKAGES PACKAGES.gz [A-Za-z]*-package.Rd FALSE.* mirrors.html
 
 test-Translation:
@@ -495,15 +495,16 @@ test-Packages-Recommended:
 
 test-Packages1-Recommended:
 	@test -d RecPackages || mkdir RecPackages
-	@for p in $(R_PKGS_RECOMMENDED); do \
+	@fail=; for p in $(R_PKGS_RECOMMENDED); do \
 	  rm -Rf RecPackages/$${p}; \
 	  gzip -dc "$(top_srcdir)/src/library/Recommended/$${p}.tgz" | \
 	    (cd RecPackages && $(TAR) -x -f -) ; \
 	  $(ECHO) "checking package '$${p}'"; \
 	  R_LIBS="$(top_builddir)/library:$${R_LIBS}" \
-	    _R_CHECK_FORCE_SUGGESTS_=FALSE $(R3) --install=skip \
-	    --library="$(top_builddir)/library" RecPackages/$${p} || $(ECHO); \
-	done
+	  _R_CHECK_FORCE_SUGGESTS_=FALSE \
+	  $(RCHK) --install=skip --library="$(top_builddir)/library" \
+	    RecPackages/$${p} || fail="$${fail} $${p}"; \
+	done; if test -n "$${fail}"; then $(ECHO) "FAILED:$${fail}"; exit 1; fi
 
 PKG_ROBJECTS = $(R_PKGS_RECOMMENDED:=.log)
 
@@ -523,8 +524,8 @@ stamp-Packages2: $(PKG_ROBJECTS)
 	    (cd RecPackages && $(TAR) -x -f -) ; \
 	  $(ECHO) "begin checking package '$${p}'"; \
 	  R_LIBS="$(top_builddir)/library:$${R_LIBS}" \
-	 _R_CHECK_FORCE_SUGGESTS_=FALSE $(R3) --install=skip \
-	    --library="$(top_builddir)/library" RecPackages/$${p}  > $@ 2>&1
+	 _R_CHECK_FORCE_SUGGESTS_=FALSE $(RCHK) --install=skip \
+	    --library="$(top_builddir)/library" RecPackages/$${p}  > $@ 2>&1 || (cat $@ && exit 1)
 	@cat $@
 
 INSTFILES = README \
